In [25]:
import pandas as pd

df = pd.read_csv("/workspaces/project.final_allocation/notebook/ambulance_combined_dataset 2.csv")
df

,datetime,latitude,longitude,emergency_type,hour,day,traffic_level,temperature,rain,demand
0,10-12-2015 17:40,40.297876,-75.581294,EMS,17,Thursday,0.562178,38,0,1
1,10-12-2015 17:40,40.258061,-75.264680,EMS,17,Thursday,0.965500,21,0,1
2,10-12-2015 17:40,40.121182,-75.351975,Fire,17,Thursday,0.812396,20,0,1
3,10-12-2015 17:40,40.116153,-75.343513,EMS,17,Thursday,0.719061,33,0,1
4,10-12-2015 17:40,40.251492,-75.603350,EMS,17,Thursday,0.409213,21,0,1
...,...,...,...,...,...,...,...,...,...,...
99487,24-08-2016 11:06,40.132869,-75.333515,Traffic,11,Wednesday,0.833602,25,1,1
99488,24-08-2016 11:07,40.006974,-75.289080,Traffic,11,Wednesday,0.359906,29,0,1
99489,24-08-2016 11:12,40.115429,-75.334679,EMS,11,Wednesday,0.601142,25,0,1
99490,24-08-2016 11:17,40.186431,-75.192555,EMS,11,Wednesday,0.594402,38,0,1
99491,24-08-2016 11:17,40.207055,-75.317952,Traffic,11,Wednesday,0.944539,26,0,1

In [26]:
df.isna().sum()

datetime          0
latitude          0
longitude         0
emergency_type    0
hour              0
day               0
traffic_level     0
temperature       0
rain              0
demand            0
dtype: int64

In [27]:
df.to_csv("/workspaces/project.final_allocation/notebook/ambulance_updated_dataset.csv", index=False)
df

,datetime,latitude,longitude,emergency_type,hour,day,traffic_level,temperature,rain,demand
0,10-12-2015 17:40,40.297876,-75.581294,EMS,17,Thursday,0.562178,38,0,1
1,10-12-2015 17:40,40.258061,-75.264680,EMS,17,Thursday,0.965500,21,0,1
2,10-12-2015 17:40,40.121182,-75.351975,Fire,17,Thursday,0.812396,20,0,1
3,10-12-2015 17:40,40.116153,-75.343513,EMS,17,Thursday,0.719061,33,0,1
4,10-12-2015 17:40,40.251492,-75.603350,EMS,17,Thursday,0.409213,21,0,1
...,...,...,...,...,...,...,...,...,...,...
99487,24-08-2016 11:06,40.132869,-75.333515,Traffic,11,Wednesday,0.833602,25,1,1
99488,24-08-2016 11:07,40.006974,-75.289080,Traffic,11,Wednesday,0.359906,29,0,1
99489,24-08-2016 11:12,40.115429,-75.334679,EMS,11,Wednesday,0.601142,25,0,1
99490,24-08-2016 11:17,40.186431,-75.192555,EMS,11,Wednesday,0.594402,38,0,1
99491,24-08-2016 11:17,40.207055,-75.317952,Traffic,11,Wednesday,0.944539,26,0,1

In [28]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['emergency_type'] = le.fit_transform(df['emergency_type'])

In [29]:
df['datetime']=le.fit_transform(df['datetime'])
df['emergency_type']=le.fit_transform(df['emergency_type'])
df['day']=le.fit_transform(df['day'])

In [30]:
import numpy as np

In [31]:
df['priority'] = np.select(
    [
        df['emergency_type'] <= 2,   # LOW
        df['emergency_type'] <= 5,   # MEDIUM
        df['emergency_type'] > 5     # HIGH
    ],
    [0, 1, 2]
)

In [32]:
print(df['priority'].value_counts())

priority
0    99492
Name: count, dtype: int64

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   datetime        99492 non-null  int64
 1   latitude        99492 non-null  float64
 2   longitude       99492 non-null  float64
 3   emergency_type  99492 non-null  int64
 4   hour            99492 non-null  int64
 5   day             99492 non-null  int64
 6   traffic_level   99492 non-null  float64
 7   temperature     99492 non-null  int64
 8   rain            99492 non-null  int64
 9   demand          99492 non-null  int64
 10  priority        99492 non-null  int64
dtypes: float64(3), int64(8)
memory usage: 8.3 MB

In [34]:
df.columns

Index(['datetime', 'latitude', 'longitude', 'emergency_type', 'hour', 'day',
       'traffic_level', 'temperature', 'rain', 'demand', 'priority'],
      dtype='str')

In [35]:
X = df.drop(labels=['demand'], axis=1)
Y = df['demand']

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X['emergency_type'] = le.fit_transform(X['emergency_type'])

In [37]:
X['datetime']=le.fit_transform(X['datetime'])
X['emergency_type']=le.fit_transform(X['emergency_type'])
X['day']=le.fit_transform(X['day'])

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_pre = scaler.fit_transform(X)

In [39]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(
    X_pre, Y, test_size=0.2, random_state=42
)

In [40]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(xtrain, ytrain)

RandomForestClassifier()

In [41]:
train_score = model.score(xtrain, ytrain)
test_score = model.score(xtest, ytest)

print("Train Accuracy:", train_score)
print("Test Accuracy:", test_score)

Train Accuracy: 0.9999497443242497
Test Accuracy: 0.9488919041157847

In [42]:
ytrain_pred = model.predict(xtrain)
ytest_pred = model.predict(xtest)

In [43]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(ytest, ytest_pred)
print(cm)

[[18760    74     1     0]
 [  861   119     0     0]
 [   77     1     2     0]
 [    3     0     0     1]]

In [44]:
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

In [45]:
import pickle
import numpy as np

def smart_prediction(data):
    
    # load model & scaler
    with open('/workspaces/project.final_allocation/notebook/model.pkl', 'rb') as f:
        model = pickle.load(f)
        
    with open('/workspaces/project.final_allocation/notebook/scaler.pkl', 'rb') as f:
        scaler = pickle.load(f)

    # scale input
    data_scaled = scaler.transform([data])

    # prediction
    demand = model.predict(data_scaled)[0]

    # 🚑 ambulance allocation logic
    if demand == 1 and data[3] > 0.7:
        ambulances = 3
        level = "HIGH"
    elif demand == 1:
        ambulances = 2
        level = "MEDIUM"
    else:
        ambulances = 1
        level = "LOW"

    # ⏱️ response time (simple logic)
    response_time = 10 + (data[3] * 10)   # traffic based

    return {
        "Demand": int(demand),
        "Priority": level,
        "Ambulances": ambulances,
        "Response Time": round(response_time, 2)
    }

In [46]:
latitude = 40.2
longitude = -75.3
hour = 18
traffic = 0.8
temperature = 32
rain = 5
demand = 1
priority = 3
day = 2
month = 5

sample = [latitude, longitude, hour, traffic, temperature , demand, priority , day , month,hour]

result=smart_prediction(sample)

print(result)

{'Demand': 1, 'Priority': 'HIGH', 'Ambulances': 3, 'Response Time': 18.0}

/home/codespace/.local/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(